### ISSUE TITLE
How are the image embeddings being set to LayoutLM model?

### ISSUE THREAD

**Issue by ravilkashyap** [NielsRogge/Transformers-Tutorials#1]
Thankyou for the notebook on using LayoutLM model. I am not able to figure out the part where we are sending image embeddings through Faster-RCNN. This code only relies on text is it?

**Comment by NielsRogge** [comment]
Hi,

The implementation I'm using does not add image embeddings indeed. However, as Faster-RCNN seemed rather complex to me, I'm currently working on adding features from Facebook AI's DETR.

**Comment by NielsRogge** [comment]
Hi @ravilkashyap @alejandrojcastaneira, 

As there was a lot of demand for this, I've created a notebook that illustrates how to add image embeddings from a pre-trained backbone to LayoutLM: https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLM/Add_image_embeddings_to_LayoutLM.ipynb
