### ISSUE TITLE
Is the dataloader code from the LayoutLMv2 ipynb file still valid?

### ISSUE THREAD

**Issue by plamb-viso** [NielsRogge/Transformers-Tutorials#103]
I've been following along this tutorial https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLMv2/RVL-CDIP/Fine_tuning_LayoutLMv2ForSequenceClassification_on_RVL_CDIP.ipynb

However, I may be using newer versions since this was written.

In this tutorial, the features for the encoded dataset are built using classes from the huggingface datasets library, for e.g.:

```python
features = Features({
        'image': Array3D(dtype="int64", shape=(3, 224, 224)),
        'input_ids': Sequence(feature=Value(dtype='int64')),
        'attention_mask': Sequence(Value(dtype='int64')),
        'token_type_ids': Sequence(Value(dtype='int64')),
        'bbox': Array2D(dtype="int64", shape=(512, 4)),
        'labels': ClassLabel(num_classes=len(labels), names=labels),
    })
```
This setup appears to return python lists for things like input_ids and bbox.

However, this pretrained model being called during training has this forward pass method:
https://github.com/microsoft/unilm/blob/master/layoutlmft/layoutlmft/models/layoutlmv2/modeling_layoutlmv2.py#L675

And all of the manipulations it does to its parameters appear to expect pytorch objects. For e.g. [inputs_ids gets `.size()` called on it](https://github.com/microsoft/unilm/blob/master/layoutlmft/layoutlmft/models/layoutlmv2/modeling_layoutlmv2.py#L700) and [bbox should have a `dtype`](https://github.com/microsoft/unilm/blob/master/layoutlmft/layoutlmft/models/layoutlmv2/modeling_layoutlmv2.py#L721)

Was this tutorial written on a different version of `microsoft/layoutlmv2-base-uncased` and needs to be updated to pass these values as torch objects?

**Comment by NielsRogge** [comment]
Hi,

I'm turning everything into PyTorch tensors later on:

```python
encoded_dataset.set_format(type="torch", device="cuda")
```

**Comment by plamb-viso** [comment]
Wow thanks @NielsRogge I am not sure how I missed that line while reading
