### ISSUE TITLE
Input image size doesn't match model

### ISSUE THREAD

**Issue by dhea1323** [NielsRogge/Transformers-Tutorials#107]
Hello @NielsRogge and community,

I tried to combine ```microsoft/beit-base-patch16-224``` and ```cahya/roberta-base-indonesian-1.5G``` just by changing the following code which is in [Fine_tune_TrOCR_on_IAM_Handwriting_Database_using_native_PyTorch.ipynb](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/TrOCR/Fine_tune_TrOCR_on_IAM_Handwriting_Database_using_native_PyTorch.ipynb) with my own dataset
```python
encode = 'microsoft/beit-base-patch16-224'
decode = 'cahya/roberta-base-indonesian-1.5G'

feature_extractor=ViTFeatureExtractor.from_pretrained(encode)
tokenizer = RobertaTokenizer.from_pretrained(decode)
processor = TrOCRProcessor(feature_extractor=feature_extractor, tokenizer=tokenizer)

train_dataset = IAMDataset(root_dir='/path/to/dataset/',
                           df=train_df,
                           processor=processor)
eval_dataset = IAMDataset(root_dir='/path/to/dataset/',
                           df=test_df,
                           processor=processor)

model = VisionEncoderDecoderModel.from_encoder_decoder_pretrained(encode, decode)
```
The following error occurs: ```ValueError: Input image size (384*384) doesn't match model (224*224)```

Is there anything else that must be adjusted? or Is there any mistake I did?, because when I try to run the file with my own dataset without changing anything, no error occurs. 

Thank you.

**Comment by dhea1323** [comment]
Error occurs in the program in the following line ```outputs = model(**batch)```,
```python
for epoch in range(10):  # loop over the dataset multiple times
   # train
   model.train()
   train_loss = 0.0
   for batch in tqdm(train_dataloader):
      # get the inputs
      for k,v in batch.items():
        batch[k] = v.to(device)

      # forward + backward + optimize
      outputs = model(**batch)
      loss = outputs.loss
      loss.backward()
      optimizer.step()
      optimizer.zero_grad()

      train_loss += loss.item()

   print(f"Loss after epoch {epoch}:", train_loss/len(train_dataloader))
```

**Comment by dhea1323** [comment]
Already solved

**Comment by archwolf118** [comment]
> Already solvedAlready solved

How you solved this problem?

**Comment by hokhaminh** [comment]
> Already solved

bro, how do you solved this ??

**Comment by NielsRogge** [comment]
You can check `feature_extractor.size` to see the size that will be used when resizing images. Note that a multimodal model like TrOCR consists of a feature extractor for preparing the images, and a tokenizer for preparing the text targets. A processor combines both.
