### ISSUE TITLE
Question about LayoutLMv2-large Finetuning & LayoutLMv3

### ISSUE THREAD

**Issue by yellowjs0304** [NielsRogge/Transformers-Tutorials#109]
Hi, @NielsRogge Thank you for sharing nice work.
I'm a first in huggingface, so i have some question in finetuning models.

Can I use the LayouLMv2-large model at fine-tuning with my own dataset?
I figured out by your workbook, how to using the layoutlmv2-base-uncased models.

But, When I tried to change the model name as below, It saids like this Error.
```
    model_name="microsoft/layoutlmv2-large-uncased"
    processor = LayoutLMv2Processor.from_pretrained(model_name, revision="no_ocr")
```
![image](https://user-images.githubusercontent.com/30281608/165218092-28840457-1d7e-4e71-9560-40bc733feba2.png)

I think there's no preprocessor_config.json file in [lmv2-large](https://huggingface.co/microsoft/layoutlmv2-large-uncased/tree/main) page.
How can i use this model?

Also, Do you have any detailed plan for release the LayoutLMv3 on transformers? 
(if could, the sample code like in this repo will be really good help)

Thank you!

**Comment by LucaMalagutti** [comment]
Regarding your question about using the LayoutLMv2-large model without OCR, unfortunately there isn't a "no_ocr" revision for the [layoutlmv2-large model](https://huggingface.co/microsoft/layoutlmv2-large-uncased/tree/main). If you want to use the large version of layoutLMv2 without OCR, you can download the large model locally, and copy the `preprocessor_config.json` file from [the base version](https://huggingface.co/microsoft/layoutlmv2-base-uncased/tree/no_ocr). You will then be able to load the large model using `from_pretrained()` on your local model folder

**Comment by yellowjs0304** [comment]
Thank you for your reply. After your commented, now the file has been added.

Now, I can train the large model like below. Thank you.
```
processor = LayoutLMv2Processor.from_pretrained(model_name, apply_ocr=False)
# Train the Model
model = LayoutLMv2ForTokenClassification.from_pretrained(model_name, num_labels=len(labels))
```
