### ISSUE TITLE
LayoutLMv2 and LayoutXLM

### ISSUE THREAD

**Issue by TahaDouaji** [NielsRogge/Transformers-Tutorials#11]
Thank you so much for these great tutorials, they are really helpful
I was wondering if you have any plans to make a new tutorial for LayoutLMv2 or LayoutXLM in the near future?
Thank you again!

**Comment by NielsRogge** [comment]
Hi,

Yes LayoutLMv2 is currently being added to HuggingFace Transformers, so I might make a tutorial on that one when it's merged. Regarding LayoutXLM, is it any different from LayoutLM?

**Comment by TahaDouaji** [comment]
Hi,
I guess there is no major difference between both of them, but since LayoutXLM is multilingual, it may be interesting for people "Like me" who want to build a non English model.
also LayoutLMv2 & LayoutXLM are merged into [https://github.com/microsoft/unilm](unilm) master branch
Thank you!
