### ISSUE TITLE
[HELP] Layoutlmv2 with custom dataset error - UndefinedMetricWarning: Precision and F-score are ill-defined

### ISSUE THREAD

**Issue by sankalp-wns** [NielsRogge/Transformers-Tutorials#117]
I am trying **LayoutLMV2** with a **custom dataset** (following [this](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLMv2/FUNSD/Fine_tuning_LayoutLMv2ForTokenClassification_on_FUNSD.ipynb) notebook) and keep getting the below error while model training -

`python3.7/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division`parameter to control this behavior.` 

The code runs for `load_dataset("nielsr/funsd")` and my custom dataset follows the same structure as this dataset.

Where am I going wrong? Can you put me in the right direction?

**Comment by NielsRogge** [comment]
Hi,

I would check if the labels are created properly.

**Comment by sankalp-wns** [comment]
I ensured by drawing the bounding boxes and labels on the image - they are correct. Also made sure all documents have all the tags. The only doubtful thing I feel is that the tokens that I want to predict appear only ones or twice per document. So could it be due to the low probability of its appearance in the document? Also, should I increase the dataset? currently, I have only 250 documents to train with.

**Comment by sankalp-wns** [comment]
> Hi,
> 
> I would check if the labels are created properly.

Indeed the error was due to the labels. I was using BIO tagging and the 'I' tags were missing. Fixed and working now. Thank you.

**Comment by munish0838** [comment]
Hi @sankalp-wns could you please share how to create custom labels for dataset, any nomenclature to be followed, no of labels etc.
Thank You

**Comment by sankalp-wns** [comment]
A simple UI was created by superimposing bounding boxes on the image and allowing a user to select fields to train on. Initially, I followed BIO tagging but some of the fields had a singular value (eg: city name, zipcode, etc) so ended up using only the B-tag and custom logic to combine multiple words with the same tag ('address' tag for - "221B Bakers street"). I was able to train as many as 20 fields on ~600 documents with a score of more than 80%

**Comment by munish0838** [comment]
> 

Thanks a lot. Really appreciate the quick response
