### ISSUE TITLE
save and load fine tuned Vision Transformer

### ISSUE THREAD

**Issue by daquarti** [NielsRogge/Transformers-Tutorials#12]
trainer.save_model(path)

model = ViTForImageClassification.from_pretrained(path)

The path is correct but an error appears because is not the config.json file

Could you help me?
Thanks

**Comment by NielsRogge** [comment]
Hmm normaly that should work. Do you have a Colab to reproduce?

**Comment by daquarti** [comment]
I found the error: ViTFeatureExtractor.save_pretrained() generates "preprocessor_config.json"  instead  "config.json"
Thanks
