### ISSUE TITLE
How to create own dataset from open source tool for LayoutLMv3?

### ISSUE THREAD

**Issue by jyotiyadav94** [NielsRogge/Transformers-Tutorials#121]
A couple of tools I found interesting were 
Paid tool (Trail Version)- UBIAI I am able to create the dataset FUNSD but in the format of LayoutLMV1 I am not sure if I can use the same for LayoutLMV3 because it also takes into account an extra new Image feature.

Open source - LabelStudio, LabelMe, VGG, and Inception.
Is there anyone who tried the same format of LayoutLMV3 dataset format by creating it from an open-source tool?

**Comment by renjithsasidharan** [comment]
I have used Labelstudio, you will have to convert the annotations created by label studio to list of words, boxes.

**Comment by jyotiyadav94** [comment]
Thank you @renjithsasidharan I am able to create the custom dataset using VGG annotation tool .
Hence I am closing this ticket.

**Comment by Mahmuod1** [comment]
i see label called ner_tags in features class label how i can create them with labelstudio of VGG annotation tool
