### ISSUE TITLE
LayoutLMV3 FUNSD Class label -100 less than -1 error on Google colab

### ISSUE THREAD

**Issue by schartz** [NielsRogge/Transformers-Tutorials#126]
Hello @NielsRogge .
Thanks a lot for this awesome resource. I am learning about layoutLMV3. I tried running [Fine_tune_LayoutLMv3_on_FUNSD_(HuggingFace_Trainer).](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLMv3/Fine_tune_LayoutLMv3_on_FUNSD_(HuggingFace_Trainer).ipynb) notebook in Google Colab and was face with following runtime error:

```
ValueError                                Traceback (most recent call last)
[<ipython-input-40-bfd7a3492b2e>](https://localhost:8080/#) in <module>()
     14     batched=True,
     15     remove_columns=column_names,
---> 16     features=features,
     17 )
     18 eval_dataset = dataset["test"].map(

13 frames
[/usr/local/lib/python3.7/dist-packages/datasets/features/features.py](https://localhost:8080/#) in cast_storage(self, storage)
   1016             min_max = pc.min_max(storage).as_py()
   1017             if min_max["min"] < -1:
-> 1018                 raise ValueError(f"Class label {min_max['min']} less than -1")
   1019             if min_max["max"] >= self.num_classes:
   1020                 raise ValueError(

ValueError: Class label -100 less than -1
```

Colab is highlighting the error at :
```
train_dataset = dataset["train"].map(
    prepare_examples,
    batched=True,
    remove_columns=column_names,
    features=features,
)
```

on `features=features` line in particular. 

I did not make any change in the notebook. I was simply reading and executing the cells.
Any help would be greatly appreciated.

**Comment by NielsRogge** [comment]
Thanks for reporting, it's a mistake on my side, the labels should be of type `datasets.Sequence(feature=datasets.Value(dtype='int64'))`, rather than `ClassLabel`. I've fixed it in my repo.
