### ISSUE TITLE
word level predictions are more than the actual number of words

### ISSUE THREAD

**Issue by Momentum-TN** [NielsRogge/Transformers-Tutorials#13]
Hi @NielsRogge,

Thank you for the amazing contribution that you made.
I noticed in the [Fine tuning notebook](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLM/Fine_tuning_LayoutLMForTokenClassification_on_FUNSD.ipynb) that the number of words detected with pytesseract (164 in the notebook) are less than the number of word level predictions (229 in the notebook) even after eliminating the special tokens. It is supposed that they are equal. How to make it ?

Thanks in advance

**Comment by NielsRogge** [comment]
Hi @dcyoung,

Regular tokenizers don't support offset mappings. I've got a new notebook that explains how to do inference on new document images when no label information is accessible, you can find it [here](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLMv2/FUNSD/True_inference_with_LayoutLMv2ForTokenClassification_%2B_Gradio_demo.ipynb).
