### ISSUE TITLE
layoutlmv2- CORD How to make real time inference with passing a single image in layoutlmv2/layoutlmv3

### ISSUE THREAD

**Issue by jyotiyadav94** [NielsRogge/Transformers-Tutorials#132]
I am new to the CORD dataset. I would like to ask you if we can make an inference by passing an image as input to the trained model 
and getting the output - https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLMv2/CORD/Fine_tuning_LayoutLMv2ForTokenClassification_on_CORD.ipynb

**Comment by NielsRogge** [comment]
Hi,

There's a HuggingFace Space here: https://huggingface.co/spaces/katanaml/LayoutLMv2-CORD.

You can check the [app.py](https://huggingface.co/spaces/katanaml/LayoutLMv2-CORD/blob/main/app.py)  to see the inference code.

**Comment by abaranovskis-redsamurai** [comment]
Hi,

Colab notebooks for CORD dataset preparation, LayoutLMv2 model fine-tuning and inference with CORD data you can find here: https://github.com/katanaml/sparrow/tree/main/sparrow-research

**Comment by jyotiyadav94** [comment]
Thanks @NielsRogge & @abaranovskis-redsamurai

**Comment by jyotiyadav94** [comment]
@NielsRogge  , @abaranovskis-redsamurai ,

Is there any inference code for the layoutlmv3 as well for the CORD dataset?
I found this for FUNSD dataset - https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLMv3/Fine_tune_LayoutLMv3_on_FUNSD_(HuggingFace_Trainer).ipynb
