### ISSUE TITLE
colab link order may be wrong

### ISSUE THREAD

**Issue by Everfighting** [NielsRogge/Transformers-Tutorials#14]
link 
Fine_tuning_LayoutLMForSequenceClassification_on_RVL_CDIP.ipynb 
to 
fine-tuning LayoutLMForTokenClassification on the FUNSD dataset

whereas  link 
Fine_tuning_LayoutLMForTokenClassification_on_FUNSD.ipynb
to 
fine-tuning LayoutLMForSequenceClassification on the RVL-CDIP dataset

**Comment by NielsRogge** [comment]
Thanks, should be fixed now.
