### ISSUE TITLE
How to get the input word?

### ISSUE THREAD

**Issue by yellowjs0304** [NielsRogge/Transformers-Tutorials#143]
Hi, I used LayoutLMv2 Inference [code](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLMv2/FUNSD/Inference_with_LayoutLMv2ForTokenClassification.ipynb).

It looks like the true_prediction, true_labels, true_bbox is not match with gt data. 
In detail, I used seperate OCR results(there's 45 pairs of data (boxes and their words))
But the true_prediction, labels, bboxes have 50 pairs.
I think maybe the reason is LayoutLMv2 Tokenizer.

What I really wonder is How can i get the seperated tokens(from Tokenizer).
I already used tokenizer.batch_decode function, but It looks not same with tokenizer's return.
```
text = tokenizer2.batch_decode(encoding['input_ids'])[0]
```

How to get the data pairs that are input to the model? 
Also, what I really wanting is to create a "Word":"predicted Entity" pair. Please give me some tip about it.

**Comment by fraps12** [comment]
First of all Tokenizer uses vocab provided by microsoft by default. So if you feed to model word "Training" it will be splitted for something like "Train" and "ing". That is reason why you have more pairs from prediction but if you filter the output with `id2label[pred] for idx, pred in enumerate(s_predictions) if not is_subword[idx]` you will have same number of prediction as words feeded to model.
There are only 1 limitation. You don't know how much words you can really feed to model as input. If there will be every word splitted by tokenizer model will just skip the half of total words.
I made a while loop which is breaking when number of real predictions is equal with number of words fed to model as input.
Real predictions i mean that predictions that have same boundingBox as that word in input to model.

To look how words was splitted. If you have combined feature_extractor and tokenizer with **LayoutLMv2Processor** you can use LayoutLMv2Processor(feature_extractor, tokenizer).tokens()

**Comment by yellowjs0304** [comment]
@fraps12 Thank you for the comment, I understood what you told,
And I have additional question, about the LayoutLMv2.

the LayoutLMv2 [tutorial code](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLMv2/FUNSD/Inference_with_LayoutLMv2ForTokenClassification.ipynb) on FUNSD this had BIO tag right now.
But in CORD data tutorial step, There's no BIO tag in data.
l'm a little bit confused about it. I heard the LayoutLMv2 used BIO tag for for finetuning (I saw in LayoutLMv2 paper)
![image](https://user-images.githubusercontent.com/30281608/181307935-0b7ca8c9-fab3-42da-98e5-5b9654f1f75e.png)

Do you know the reason about it?

**Comment by fraps12** [comment]
@yellowjs0304 Can't answer. I only can assume that is some specific modifications to layoutlmv2 model to resolve some specific task. There is really no BIO tags in any of that datasets as far as i know.

**Comment by yellowjs0304** [comment]
@fraps12 okay, Thanks for quick reply.
