### ISSUE TITLE
[LayoutLMv2 Notebook] Error while preprocess_data()

### ISSUE THREAD

**Issue by QuentinBriand** [NielsRogge/Transformers-Tutorials#147]
Hi @NielsRogge I love your works and the tons of tutorials you have :D, unfortunately I can't run your FUNSD LayoutLMv2 [notebook](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLMv2/FUNSD/Fine_tuning_LayoutLMv2ForTokenClassification_on_FUNSD.ipynb). I achieved to load your funsd dataset (nielsr/funsd) and I get the same outputs as you but unfortunately when it comes to pre-process those data I get an error. When mapping the train and test splits with the function ```preprocess_data``` I get this error 

![image](https://user-images.githubusercontent.com/91741405/179964227-fe329a8b-b975-4f85-bb55-94d82579432a.png)

Do you maybe have an idea on how could I solve this error ? I tried multiple versions of python and dataset module but it doesn't seem to solve this issue.

**Comment by NielsRogge** [comment]
Hi,

Thanks for reporting. It’s a mistake on my side, the ‘labels’ are actually of type `datasets.Sequence(feature=datasets.Value(dtype='int64'))`, rather than `ClassLabel`.
