### ISSUE TITLE
Add LILT model to transformer library 

### ISSUE THREAD

**Issue by vishal-nayak1** [NielsRogge/Transformers-Tutorials#160]
Hi,

Can you please add LILT model to transformer library as code structure is quiet similar to Layoutlmv2 model?
Repo- https://github.com/jpWang/LiLT

**Comment by vishal-nayak1** [comment]
paper- https://arxiv.org/abs/2202.13669

**Comment by NielsRogge** [comment]
Thanks for suggesting, it has been added! https://huggingface.co/docs/transformers/main/en/model_doc/lilt
