### ISSUE TITLE
Output size is 561x768 instead of 512x768

### ISSUE THREAD

**Issue by NehaMotlani** [NielsRogge/Transformers-Tutorials#17]
Hello,

I am trying to build my own classifier head over LayoutLMv2Model using HuggingFace Transformers. But the size of the output of LayoutLMv2Model is 561x768 instead of 512x768. Is this an error or am I missing something? Here is the link to my notebook - https://colab.research.google.com/drive/1FwO7E-CrXTYTERajuIgmAV8VP4J5UfvR?usp=sharing

Thank you in advance, your responses and notebooks have really helped me!

**Comment by NielsRogge** [comment]
Hi,

Yes that's normal. As explained in the [docs](https://huggingface.co/transformers/master/model_doc/layoutlmv2.html), the sequence length of LayoutLMv2 is 512 + 7*7 = 561. This is because the model fuses text tokens and image tokens together.

**Comment by NehaMotlani** [comment]
Thank you, that makes sense but how should I turn attention_mask and labels of the size of 561 as there are of size 512 using LayoutLMv2Processor. Here is the code snippet where I am getting the error - 

        sequence_output = outputs[0]
        sequence_output[0] = sequence_output[0]
        sequence_output = self.dropout(sequence_output)
        logits = self.classifier(sequence_output)
        loss = None
        if labels is not None:
            loss_fct = nn.CrossEntropyLoss()

            if attention_mask is not None:
                active_loss = attention_mask.view(-1) == 1
                active_logits = logits.view(-1, self.num_labels)[active_loss] // on this line
                active_labels = labels.view(-1)[active_loss]
                loss = loss_fct(active_logits, active_labels)
            else:
                loss = loss_fct(logits.view(-1, self.num_labels), labels.view(-1))

And the error I am getting is this - IndexError: The shape of the mask [512] at index 0 does not match the shape of the indexed tensor [561, 7] at index 0. I would really appreciate your guidance on this.

**Comment by NielsRogge** [comment]
As can be seen in the code of `LayoutLMv2ForTokenClassification`, the classification head is placed on top of the final hidden states (`sequence_output`) of only the text tokens as can be seen [here](https://github.com/huggingface/transformers/blob/8b2de0e483bc518b282ea7cb2cdea52718c2ed29/src/transformers/models/layoutlmv2/modeling_layoutlmv2.py#L1179-L1180).

**Comment by NehaMotlani** [comment]
Thanks a lot! I was able to run it after implementing what you suggested.
