### ISSUE TITLE
TypeError: PreTokenizedEncodeInput must be Union[PreTokenizedInputSequence, Tuple[PreTokenizedInputSequence, PreTokenizedInputSequence]]

### ISSUE THREAD

**Issue by jyotiyadav94** [NielsRogge/Transformers-Tutorials#176]
https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLMv3/Fine_tune_LayoutLMv3_on_FUNSD_(HuggingFace_Trainer).ipynb

I try to use the custom dataset and I execute the above I get the error 
TypeError: PreTokenizedEncodeInput must be Union[PreTokenizedInputSequence, Tuple[PreTokenizedInputSequence, PreTokenizedInputSequence]]
Can someone suggest me what could be the possible reason for this ?

![image](https://user-images.githubusercontent.com/72126242/187980330-46288003-9044-41e6-8088-c1de37bb7929.png)

![image](https://user-images.githubusercontent.com/72126242/187979876-04e62c79-bdf9-47fa-9bb2-0159129525f1.png)

@NielsRogge

**Comment by munish0838** [comment]
> 

Hi @jyotiyadav94, I am training the same model and facing this error as well
Could you please share how you were able to resolve this error

**Comment by nikhil-bante-pcpl** [comment]
did you get solution for the problem
