### ISSUE TITLE
Unable to find data - val_v1.0.json file

### ISSUE THREAD

**Issue by SGnlp** [NielsRogge/Transformers-Tutorials#18]
Hello, can you please help me locate the "val_v1.0.json" file? I am unable to find the val folder in the repo as well.
Any help will be appreciated!

with open('/content/drive/MyDrive/LayoutLMv2/Tutorial notebooks/DocVQA/val/val_v1.0.json') as f:

**Comment by NielsRogge** [comment]
Yes you can download DocVQA from the website: https://rrc.cvc.uab.es/?ch=17&com=downloads

Note that you first need to register.

**Comment by NielsRogge** [comment]
I have improved the notebook a bit, I've also added an inference section.
