### ISSUE TITLE
Getting confidence scores from Donut classification model

### ISSUE THREAD

**Issue by anaasanin** [NielsRogge/Transformers-Tutorials#193]
I was following the notebook that fine-tunes Donut on RVL-CDIP and I'm wondering how could I get confidence scores from the model output?

**Comment by NielsRogge** [comment]
Hi,

Donut only gives you confidence scores per token that it generates. You can get them by passing `return_scores=True` to the [generate](https://huggingface.co/docs/transformers/v4.22.2/en/main_classes/text_generation#transformers.generation_utils.GenerationMixin.generate) method.
