### ISSUE TITLE
TrOCR for right to left languages

### ISSUE THREAD

**Issue by MehreenMehreen** [NielsRogge/Transformers-Tutorials#197]
Hi NielsRogge

Thank you for the excellent tutorials on TrOCR. I have a question about right to left languages, e.g., Arabic and Urdu. Would it still be ok to use the ViT as encoder? Do we need a new feature extractor for images as the sentence starts from the right and ends on the left? Are the feature extractor images for ViT not extracted in a left to right manner? 

As an example, for Arabic, would the current method of using ViT as encoder and Arabic Bert model as decoder still work?

**Comment by NielsRogge** [comment]
Yes that should work!

**Comment by MehreenMehreen** [comment]
Thank you!
