### ISSUE TITLE
Custom Dataset for LayoutLMv2

### ISSUE THREAD

**Issue by DanielCarrami** [NielsRogge/Transformers-Tutorials#21]
Hi Niels. First of all, congratulations on your incredible tutorials! They are really impressive.

I'm very interested in making Fine-tuning to LayoutLMv2, similar to what you did on Fine-tuning LayoutLMv2ForTokenClassification on CORD.ipynb with the receipt's information. But I can't wrap my head around the data pre-processing. 
I want to use my own dataset for fine-tuning. I have hundreds of images ready to be annotated, but I don't know how to do it. I've seen in the other tutorials that all the datasets used in fine-tuning have the annotations in JSON format. I only know how to do them in XML PASCAL VOC format. Is there a specific way to create a custom dataset to be used by LayoutLMv2?

I would really appreciate some guidance. Again, congratulations on your tutorials and progress.

**Comment by NielsRogge** [comment]
Hi,

Thanks for the kind message. Regarding data preparation, one typically needs an annotation tool. For example, as described in the [CORD paper](https://openreview.net/forum?id=SJl3z659UH):

> For more efficient annotation, we developed a web-based annotation tool and provided it to crowd
workers.

I'm not an expert on annotation tools, but here are some I know:

* Tagalog: https://www.nlp.town/tagalog/
* TagTog: https://www.tagtog.net/

**Comment by saravind2095** [comment]
Hi @DanielCarrami and @NielsRogge ,

Are the annotation tool for CORD what you mentioned is still available? 
If they are any please, tell us. Thanks in advance.
