### ISSUE TITLE
more than 512 tokens 

### ISSUE THREAD

**Issue by naveenjr** [NielsRogge/Transformers-Tutorials#23]
how to handle the input image have more than 512 tokens or words in an image in Layout LM2 tokenizer example ?

the visual representation is stopping certain level while showing output ?

**Comment by NielsRogge** [comment]
Hi,

Yes that's a limit of current Transformer models, as the required memory + time scales quadratically with the sequence length. 

What you can do is using a sliding window approach, as explained in [this tutorial](https://github.com/huggingface/notebooks/blob/master/examples/question_answering.ipynb).

Basically, what is done is you create multiple training examples for a given document. Each training example has some overlap with another training example. You can then forward each training example through the model.

**Comment by naveenjr** [comment]
thanks @NielsRogge  for the spontaneous reply . i am able to get good result for token classification ("Inference_with_LayoutLMv2ForTokenClassification" ) with words ,coordinates ,and NER label info for a different set of  invoices ,i am wondering is there any way to map key (B-Question, I-Question) to corresponding (B-ANSWER,I-ANSWER ) ?

**Comment by jyotiyadav94** [comment]
Hi @naveenjr 

Did you find a way to train the documents with more than 512 tokens of sequence length?
