### ISSUE TITLE
AttributeError: 'TrOCRProcessor' object has no attribute 'feature_extractor'

### ISSUE THREAD

**Issue by Zahak-Anjum** [NielsRogge/Transformers-Tutorials#233]
Following your notebook for the finetuning of TrOCR using Seq2SeqTrainer I get the following error:
AttributeError: 'TrOCRProcessor' object has no attribute 'feature_extractor'

![image](https://user-images.githubusercontent.com/71014321/211219713-5401f1e5-a294-4425-b869-7f6d4b8380a5.png)

I am using google coloab for training. 

Please help me to solve this error!

**Comment by larsson-patrik** [comment]
replace `tokenizer=processor.feature_extractor` with `tokenizer=processor.image_processor`
