### ISSUE TITLE
Issue finetuning GIT with my own images/captions

### ISSUE THREAD

**Issue by ArminBaz** [NielsRogge/Transformers-Tutorials#239]
Hi there, 

I'm trying to finetune the GIT model following your tutorial. I followed the tutorial verbatim, only replacing the images with my own toy images and the captions with my own captions. However, I am running into this error:
`ValueError: Expected input batch_size (1416) to match target batch_size (1022).`

I'm not really sure how to proceed here. I am certain that its a rather simple error on my end that I am overlooking, but I could use some help.

Additionally, I used the same exact toy dataset with the new BLIP image to text model and it worked as expected. So, hopefully that can help narrow down where exactly this issue might be stemming from.

Thanks

**Comment by NielsRogge** [comment]
Hi,

Thanks for your interest in GIT/BLIP. Do you have a reproducable code snippet?

**Comment by ArminBaz** [comment]
Hey, the issue
