### ISSUE TITLE
ArrowInvalid error in Vision Transformer Notebook 

### ISSUE THREAD

**Issue by whosivan** [NielsRogge/Transformers-Tutorials#24]
Hi,

I am trying to execute the notebook and I kept encountering the error of the following

<img width="868" alt="Screen Shot 2021-09-13 at 8 40 33 PM" src="https://user-images.githubusercontent.com/24474035/133191342-84f97367-8e25-41dd-97f5-e6d8bd17a331.png">

Any pointers on solving this issue?

https://colab.research.google.com/drive/1fKZWN1Q6GcvRFBbrcdnCMLALj-OUEfg2?usp=sharing

**Comment by felipenunezb** [comment]
I had the same issue. Solved it by installing an older version of datasets:

!pip install -q datasets==1.11.0 seqeval

**Comment by NielsRogge** [comment]
Thanks for reporting, will investigate this.

**Comment by NielsRogge** [comment]
Update: the author of HuggingFace Datasets will push a hot fix and do a patch release for this.

Expect this to be fixed soon!

**Comment by NielsRogge** [comment]
Fixed with version 1.12.1. You can install again using pip: pip install datasets.
