### ISSUE TITLE
BLIP Training Tutorial？

### ISSUE THREAD

**Issue by ScottishFold007** [NielsRogge/Transformers-Tutorials#240]
A great collection of transformers tutorials, very beneficial! Absolutely amazing! Can you publish some notebook tutorials for training and fine tuning BLIP models? Thanks!

**Comment by NielsRogge** [comment]
Hi,

A notebook on fine-tuning BLIP can be found here: https://github.com/huggingface/notebooks/blob/main/examples/image_captioning_blip.ipynb.

Tip: if you change "github.com" in the URL by "colab.research.google.com/github", it will open in Google Colab

**Comment by ScottishFold007** [comment]
> Hi,
> 
> A notebook on fine-tuning BLIP can be found here: https://github.com/huggingface/notebooks/blob/main/examples/image_captioning_blip.ipynb.
> 
> Tip: if you change "github.com" in the URL by "colab.research.google.com/github", it will open in Google Colab

Good. Thank you very much!
