### ISSUE TITLE
LiLT and xlm-roberta with Layoutlmv3 Processor 

### ISSUE THREAD

**Issue by TahaDouaji** [NielsRogge/Transformers-Tutorials#245]
Hello @NielsRogge 
Thank you for the LiLT notebooks, I would like to ask how to apply OCR Segments and Layoutlmv3 Processor with LiLT when using `lilt-xlm-roberta-base` model instead of `lilt-roberta-en-base`.
Thanks

**Comment by NielsRogge** [comment]
Hi,

Actually I regret using the processor for the LiLT notebook, as it's actually not required.

Take a look at [this notebook](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LiLT/Fine_tune_LiLT_on_a_custom_dataset%2C_in_any_language.ipynb), which only leverages the tokenizer. Just make sure to replace the tokenizer by

```
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")
```
