### ISSUE TITLE
GPU for "Inference_with_TrOCR_+_Gradio_demo.ipynb"

### ISSUE THREAD

**Issue by shenw000** [NielsRogge/Transformers-Tutorials#248]
I am developing an application closely following the "Inference_with_TrOCR_+_Gradio_demo.ipynb", but found it is quite slow. I monitored the GPU usage when running Inference_with_TrOCR_+_Gradio_demo.ipynb. As a results, I suspect that I haven't utilized the GPU when running the Inference_with_TrOCR_+_Gradio_demo.ipynb. Could you share with me how I can use GPU when running Inference_with_TrOCR_+_Gradio_demo.ipynb? 

Thanks in advance!

**Comment by NielsRogge** [comment]
Hi,

For any PyTorch model to be used on a GPU, you need to use the following:
```
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

model.to(device)

# also make sure to put your model inputs on the device!
pixel_values = pixel_values.to(device)
input_ids = input_ids.to(device)

# forward pass
outputs = model.generate(pixel_values, input_ids)
```

**Comment by shenw000** [comment]
Thanks, Niels Rogge!
