### ISSUE TITLE
LayoutXLM for groups of tokens classification

### ISSUE THREAD

**Issue by DanielCarrami** [NielsRogge/Transformers-Tutorials#25]
Hello again Niels!

I'm trying to use LayoutXLM (I'm working with german documents) to identify a special kind of query in invoice. So my objective is to classify sequences of words instead of just tokens.

For example, the queries can come in the form of tables. In that case, instead of classifying all the tokens on the table, I want to classify each row, like this:
![image](https://user-images.githubusercontent.com/42221062/133308255-81243114-76df-4987-8697-00937c749846.png)

I'm familiar with table extraction and detection algorithms, but the queries often come in extremely different formats, not just tables. After extensive research, I believe that LayoutLM family of algorithms can tackle my issue. 

Is there any way in which you can guide me? I already found a way to make proper annotations with the tools you mentioned in my previous issue.

**Comment by fmobrj** [comment]
I am also interested in exploring LayoutXLM. I am trying to cerate a LayoutLMv2Processor from 'microsoft/layoutxlm-base' but it does not work. So I tried to create it from 'microsoft/layoutlmv2-base-uncased' and then update the process tokenizer with a tokenizer loaded from "XLMRobertaTokenizer" and it also does not work. Any hints in how to acomplish to create Datasets/Dataloaders for LayoutXLM?
