### ISSUE TITLE
Set tesseract language

### ISSUE THREAD

**Issue by polodealvarado** [NielsRogge/Transformers-Tutorials#26]
Hi Niels!

First of all, thank you for this amazing report with all these jupyter notebooks.

I would like to know if it is possible to select the tesseract language via LayoutLMv2FeatureExtractor() and if not , how could I do it.

**Comment by NielsRogge** [comment]
Hi,

Yes that's possible, you only need to add an additional "lang" parameter add [this line(https://github.com/huggingface/transformers/blob/c783e14887474ca3f3a0e804f67fe3fc412caeda/src/transformers/models/layoutlmv2/feature_extraction_layoutlmv2.py#L54), when using `pytesseract.image_to_data`. 

Note that PyTesseract is only a Python wrapper around Tesseract, so make sure to install the data for the other language first. For more information, see [this Stackoverflow post](https://stackoverflow.com/a/44693503).

**Comment by polodealvarado** [comment]
Great, thank you so much @NielsRogge .
