### ISSUE TITLE
Detr Huggingfaces target format

### ISSUE THREAD

**Issue by caiodataopshouse** [NielsRogge/Transformers-Tutorials#264]
For training the Detr the boxes on the input target have to be [x,y,w,h] with x,y upper-left-corner coordinates or [x,y,x2,y2] with x2,y2 lower-right coordinates ? Thank you

**Comment by caiodataopshouse** [comment]
Or even [xcenter,ycenter,w,h] ? As by the tutorial with ballon dataset it seems like the model requires [x,y,w,h], but reading through the code of the model I got a little confused since it is constantly changing between the three representations.

**Comment by NielsRogge** [comment]
Hi, DETR expects COCO format, meaning (top_left_x, top_left_y, height, width). The image processor will normalize them by the image size.

**Comment by caiodataopshouse** [comment]
Hi... Thank You. It looks like image processor also converts to (xcenter,ycenter,width,height).
