### ISSUE TITLE
processor.tokenizer VS processor.feature_extractor,in [TrOCR] model

### ISSUE THREAD

**Issue by Mohammed20201991** [NielsRogge/Transformers-Tutorials#275]
I have a doubt about the init. trainer from @NielsRogge  Transformers-Tutorials ([TrOCR model](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/TrOCR/Fine_tune_TrOCR_on_IAM_Handwriting_Database_using_Seq2SeqTrainer.ipynb))  
Which one could be the correct value for passing to the tokenizer?
`processor.tokenizer` VS `processor.feature_extractor` , 
```
from transformers import default_data_collator

# instantiate trainer
trainer = Seq2SeqTrainer(
    model=model,
    tokenizer=processor.feature_extractor,
    args=training_args,
    compute_metrics=compute_metrics,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    data_collator=default_data_collator,
)
trainer.train()
```

**Comment by Mohammed20201991** [comment]
`processor.featuer_extractor `

**Comment by CYaiche** [comment]
Ok but why ? The name of the parameter is tokenizer and you give the feature_extractor. This does not makes sens, does it ?

**Comment by UoFallujah** [comment]
@CYaiche Yea, you are right, that is why I am asking I think it was in old used version, `processor.feature_extractor`  and used in the mentioned tutorial
