### ISSUE TITLE
AttributeError: 'ViltImageProcessor' object has no attribute 'pad_and_create_pixel_mask'

### ISSUE THREAD

**Issue by CarolineGao** [NielsRogge/Transformers-Tutorials#335]
When using the Fine-tuning ViLT for VQA.ipynb jupyternotebook, follow the steps, but cannot pass this code: encoding = processor.feature_extractor.pad_and_create_pixel_mask(pixel_values, return_tensors="pt"). 

It says AttributeError: 'ViltImageProcessor' object has no attribute 'pad_and_create_pixel_mask'

**Comment by NielsRogge** [comment]
It seems that this method was updated to be just called `pad` now, apologies for the breaking change.

cc @amyroberts

**Comment by NielsRogge** [comment]
I've updated the notebook, should work now. Thanks for reporting!
