### ISSUE TITLE
Why is 30 epochs used for LiLT finetuning?

### ISSUE THREAD

**Issue by vcntt** [NielsRogge/Transformers-Tutorials#338]
I am currently working on fine-tuning a LiLT model using the tutorial notebook titled "[LiLT/Fine_tune_LiLT_on_a_custom_dataset,_in_any_language.ipynb](https://github.com/NielsRogge/Transformers-Tutorials/tree/master/LiLT)".

In order to gain a better understanding of the most effective hyperparameters for fine-tuning, I am delving into various papers and articles that discuss BERT fine-tuning. Interestingly, these sources consistently suggest keeping the number of epochs low, typically within the range of 3 to 5 epochs. However, I noticed that in the tutorial notebook, we use 30 epochs for fine-tuning, which might seem contrary to the common advice. Despite this, the tutorial notebook yields good results. 

```python
training_args = TrainingArguments(output_dir="test",
                                  num_train_epochs=30,
                                  learning_rate=5e-5,
                                  evaluation_strategy="steps",
                                  eval_steps=100,
                                  load_best_model_at_end=True,
                                  metric_for_best_model="f1")
```

I'm curious to understand the rationale behind this apparent discrepancy. What am I missing?

**Comment by NielsRogge** [comment]
Hi,

To reproduce the results of the LiLT paper one can set `max_steps=2000`, as done here: https://github.com/jpWang/LiLT/tree/main#semantic-entity-recognition-on-funsd.

I've personally not really experiment with hyperparameter tuning yet, the `num_train_epochs=30` was probably taken from another notebook which I copied.

**Comment by vcntt** [comment]
> Hi,
> 
> To reproduce the results of the LiLT paper one can set `max_steps=2000`, as done here: https://github.com/jpWang/LiLT/tree/main#semantic-entity-recognition-on-funsd.
> 
> I've personally not really experimented with hyperparameter tuning, the `num_train_epochs=30` was probably taken from another notebook which I copied.

Thank you for thinking with me. Since the models are totally different it makes sense that the finetuning process is also different.
