### ISSUE TITLE
Dataloader errors in fine tuning MaskFormer for semantic segmentation

### ISSUE THREAD

**Issue by jaygala223** [NielsRogge/Transformers-Tutorials#339]
Hello @NielsRogge, Thank you for your amazing tutorial on fine-tuning MaskFormer for semantic segmentation.

I am trying to fine-tune the MaskFormer model based on your tutorial. However, I am running into some problems with the dataloader. Sometimes the training continues for one iteration before showing the error. Sometimes it doesn't. But it doesn't train for more than one iteration. Here's the screenshot of the error:
![image](https://github.com/NielsRogge/Transformers-Tutorials/assets/57001778/d07257fa-af98-4918-b6c8-45adda921609)

The code below also behaves the similar way:
![image](https://github.com/NielsRogge/Transformers-Tutorials/assets/57001778/8c18ff18-60e4-4e4f-9a1e-250c7bc92c6d)

Could you please take a look?

Here's the entire notebook if you want to take a look: https://colab.research.google.com/drive/1pE9wyx6RUmQbqyzGBpOWs-m_nCOPYQZ1?usp=sharing

PS: Superb tutorial. It was really easy to follow!

**Comment by jaygala223** [comment]
update: there were some problems with my data augmentations which were leading to empty batches. Closing this

**Comment by surajbijjahalli** [comment]
@jaygala223 I'm encountering the same error. Could you please share the solution you found.

**Comment by jaygala223** [comment]
Hello @surajbijjahalli, my problem was resolved by fixing the data preprocessing and augmentation steps. That may be the case in your code too.

**Comment by jaygala223** [comment]
Hello @BhavanaMP, I removed albumentations entirely and wrote my own augmentations. You can also try removing Albumentations and see if that's what causing the errors.

**Comment by BhavanaMP** [comment]
Thanks for your help @jaygala223 . I solved it by modifying the augmentations..
