### ISSUE TITLE
LayoutLMv3 correct OCR engine

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [NielsRogge/Transformers-Tutorials#352]
Hi Niels,

How are you?

Was looking into [`LayoutLMv2` notebook](https://colab.research.google.com/github/NielsRogge/Transformers-Tutorials/blob/master/LayoutLMv2/FUNSD/True_inference_with_LayoutLMv2ForTokenClassification_%2B_Gradio_demo.ipynb#scrollTo=z5a0-1LcndAE) that should be the same for `LayoutLMv3`.

and I noticed this sentence:

> As we can see, results aren't as good as previously. This can be explained by the fact that we're using a different OCR engine than the one that was used during fine-tuning.

I was wondering what should be the right OCR engine to use?

Thanks a lot,

Fra

**Comment by NielsRogge** [comment]
Hi mate! How are you?

The one that Microsoft used is the Azure OCR API, with segments enabled, see more info here: https://github.com/microsoft/unilm/issues/838

**Comment by FrancescoSaverioZuppichini** [comment]
> Hi mate! How are you?
> 
> The one that Microsoft used is the Azure OCR API, with segments enabled, see more info here: [microsoft/unilm#838](https://github.com/microsoft/unilm/issues/838)

Thanks a lot, well that is a bummer - damn wish this would have been OCR free :)
