### ISSUE TITLE
Image.open(image) chokes memory when preparing custom dataset

### ISSUE THREAD

**Issue by sankalptambe** [NielsRogge/Transformers-Tutorials#40]
I am training the model on my custom dataset. The processor expects  `Image.open('image').convert('RGB')` for all images. This is memory-consuming. I am creating a custom dataset on 800 train and 200 test samples.

Below is from the [documentation](https://huggingface.co/transformers/model_doc/layoutlmv2.html) .
```
processor = LayoutLMv2Processor.from_pretrained("microsoft/layoutlmv2-base-uncased", revision="no_ocr")

image = Image.open("name_of_your_document - can be a png file, pdf, etc.").convert("RGB")
words = ["hello", "world"]
boxes = [[1, 2, 3, 4], [5, 6, 7, 8]] # make sure to normalize your bounding boxes
encoding = processor(image, words, boxes=boxes, return_tensors="pt") 
```
I am not using inbuilt OCR. Why is an actual image needed here (Layoutlmv1 needed width and height only)? Is there an alternative to do this without Image.open()? Or else how to avoid huge memory consumption for the current process?

**Comment by NielsRogge** [comment]
Why is this memory consuming?

Normally, in PyTorch, dataloaders are Python generators, meaning they will only consume RAM when iterating over them.

**Comment by sankalptambe** [comment]
> 

Yes my mistake. Missed the 'yield'. Fixed that and working now.
