### ISSUE TITLE
UDOP FUNSD , not able to perform Inference

### ISSUE THREAD

**Issue by fathyshalaby** [NielsRogge/Transformers-Tutorials#401]
Hey @NielsRogge ,

I just tried to follow your tutorial: https://github.com/NielsRogge/Transformers-Tutorials/blob/master/UDOP/Fine_tune_UDOPEncoderModel_on_FUNSD_(HuggingFace_Trainer).ipynb

and I trained the model but when i try to execute the inference i portion of the notebook i get: 

ValueError: Unrecognized configuration class <class 'transformers.models.udop.configuration_udop.UdopConfig'> for this kind of AutoModel: AutoModelForTokenClassification.
Model type should be one of AlbertConfig, BertConfig, BigBirdConfig, BioGptConfig, BloomConfig, BrosConfig, CamembertConfig, CanineConfig, ConvBertConfig, Data2VecTextConfig, DebertaConfig, DebertaV2Config, DistilBertConfig, ElectraConfig, ErnieConfig, ErnieMConfig, EsmConfig, FalconConfig, FlaubertConfig, FNetConfig, FunnelConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, IBertConfig, LayoutLMConfig, LayoutLMv2Config, LayoutLMv3Config, LiltConfig, LongformerConfig, LukeConfig, MarkupLMConfig, MegaConfig, MegatronBertConfig, MobileBertConfig, MPNetConfig, MptConfig, MraConfig, MT5Config, NezhaConfig, NystromformerConfig, PhiConfig, QDQBertConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, SqueezeBertConfig, T5Config, UMT5Config, XLMConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, YosoConfig.

I'm also using the newest version of transformers from source.

Would really appreciate your help, as I would love to use it for my projects.

**Comment by fathyshalaby** [comment]
I see that this is probably a problem from transformers side as you already have a UdopForTokenClassification class in the notebook, would maybe change the line with the AutoModelForTokenClassification with model instead or just call the class itself.

**Comment by NielsRogge** [comment]
Hi,

As we defined a custom class (`UdopForTokenClassification`), you would need to use this class to perform inference. Hence you can just do:
```python
from transformers import UdopForTokenClassification

model = UdopForTokenClassification.from_pretrained("path_to_directory")
```
and proceed as explained in the notebook.
