### ISSUE TITLE
Handling Multiple Images PDFs in a Notebook and Seeking Guidance on Code Modification

### ISSUE THREAD

**Issue by AnasLahmar** [NielsRogge/Transformers-Tutorials#431]
Hi @NielsRogge

I want to thank you for the work you've done in this [notebook ](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/Idefics2/Fine_tune_Idefics2_for_JSON_extraction_use_cases_(PyTorch_Lightning).ipynb)

Please, You mentioned in your code that this notebook can be used in case one wants to work with multiple images-PDFs. 

Do you have a notebook on this subject? 

Thank you in advance for your feedback.

**Comment by NielsRogge** [comment]
Hi,

Thanks for your interest in my notebook. Yes I already have a notebook which supports multiple-page PDFs, will upload it soon. See also my reply at #429

**Comment by ML-Engineering-Parth** [comment]
Hi, please can you upload this. I have a dire need for this. Thank you so much, amazing repo btw!

**Comment by NielsRogge** [comment]
Ok I'll just upload it here: https://github.com/NielsRogge/Transformers-Tutorials/blob/master/Idefics2/Fine_tune_Idefics2_for_multi_page_PDF_question_answering_on_DUDE.ipynb

Note that memory requirements are pretty heavy (I used an A100 and had to limit the number of pages per PDF).

**Comment by sarugh4** [comment]
Amazing!!!!!! Thank you!!!

**Comment by AnasLahmar** [comment]
Great work! Thank you, @NielsRogge.
