### ISSUE TITLE
Why are instructions not masked when performing SFT on large multimodal models?

### ISSUE THREAD

**Issue by shijian2001** [NielsRogge/Transformers-Tutorials#456]
Thank you for your excellent tutorials, which have benefited me a lot. 
However, I have some questions about the **collate functions** in the following two tutorials:

1. https://github.com/NielsRogge/Transformers-Tutorials/blob/master/Idefics2/Fine_tune_Idefics2_for_multi_page_PDF_question_answering_on_DUDE.ipynb
2. https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LLaVa/Fine_tune_LLaVa_on_a_custom_dataset_(with_PyTorch_Lightning).ipynb

I noticed that in both tutorials you copied the input (question concatenated with answer) id to the label, and then only set the label of the pad token to -100 (no loss will be calculated). 
```
labels = batch["input_ids"].clone()
labels[labels == processor.tokenizer.pad_token_id] = -100
batch["labels"] = labels
```
However, as far as I understand SFT, only the loss of the answer part should be calculated, which means that we should also set the labels of all question parts to -100?

Looking forward to your reply！

**Comment by shijian2001** [comment]
@NielsRogge Sorry to bother you, but I really need your help and hope to receive your answer to this question, thank you!

**Comment by NielsRogge** [comment]
Hi,

Thanks for your question and sorry for the late reply. Yes that's right, by default we do compute a loss on all tokens, which can be considered suboptimal.

The TRL library offers the `DataCollatorForCompletionOnlyLM` class to only penalize the model on completion tokens: https://huggingface.co/docs/trl/v0.9.6/en/sft_trainer#train-on-completions-only.

**Comment by shijian2001** [comment]
Thanks! I will try it.
