### ISSUE TITLE
Truncating long sequences

### ISSUE THREAD

**Issue by TZeng20** [NielsRogge/Transformers-Tutorials#54]
Hi,

How do you usually handle long sequences (over 512 token limit) and it's corresponding image feature? 

For normal text based sequence classification, we can split the text into different parts and then assign the same class to each part. For LayoutLMV2, if we split the text down into different parts, should we also crop the image so that it corresponds to the text part? E.g. if we split a page's text into 2 sections, should we use the first half of the image for the first text section and the second half of the image for the second text section? Or can we use the same image for each text section?  

Thanks a lot for your work in integrating LayoutLM with Huggingface

**Comment by NielsRogge** [comment]
Hi,

You just need to make sure that the bounding box features (`bbox`) that you provide as input to the model correspond to the position in which they appear in the original image (`image`).

**Comment by TZeng20** [comment]
Ok thanks. So it is ok for `image` to include words that are not in `text` parameter?

**Comment by NielsRogge** [comment]
Yes, sure.
