### ISSUE TITLE
Finetune based on small model for TrOCR

### ISSUE THREAD

**Issue by yuchi328** [NielsRogge/Transformers-Tutorials#66]
Thanks for your excellent work! I have run the finetune script successfully on base model, but when using small model like:
`processor = TrOCRProcessor.from_pretrained("microsoft/trocr-small-printed")`

The following error occurs:
`TypeError: expected str, bytes or os.PathLike object, not NoneType`

So I hope you can kindly give me some help for it.

**Comment by strivedi02** [comment]
Even I am also encountering the same problem.
Have you got any solution for this?

**Comment by NielsRogge** [comment]
Hi,

Please install Transformers from master:

`!pip install git+https://github.com/huggingface/transformers.git`
