### ISSUE TITLE
TrOCR on ONNX runtime 

### ISSUE THREAD

**Issue by kaizengit** [NielsRogge/Transformers-Tutorials#69]
Great work! Could you please provide inputs or insights on how we could run inference on ONNX? Thank you.

**Comment by NielsRogge** [comment]
Pinging @lewtun here, he's an expert regarding ONNX.

**Comment by lewtun** [comment]
Hey @kaizengit, TrOCR is currently not a supported architecture in `transformers` because it involves a processor for the images. We're currently working on supporting vision models, so I'll take a look at TrOCR once we have that implemented :)

**Comment by kaizengit** [comment]
@lewtun Thanks for the feedback! Looking forward to the updates!

**Comment by IlyasMoutawwakil** [comment]
@lewtun thank you for all the work and effort. Can you tell me if it's possible to export TrOCR to ONNX with the current available tools on `transformers`, like by inheriting from  the pre built seq2seq onnx configuration?

**Comment by nextbelkadi** [comment]
@lewtun Hello , how i can speed my inference prediction in TrOCR ?

**Comment by NielsRogge** [comment]
Hi,

We know support TrOCR for ONNX! See https://github.com/huggingface/transformers/pull/19254.
