### ISSUE TITLE
How to extract the words

### ISSUE THREAD

**Issue by AarthiAlagammai** [NielsRogge/Transformers-Tutorials#7]
is there a possibility extract more than 512 words

**Comment by NielsRogge** [comment]
Most Transformer models (like LayoutLM) are pre-trained with a max sequence length of 512 tokens because of time/memory complexity. 

One possibility is to first split up the document in different parts, and then apply LayoutLM on each part.

**Comment by jyothish-mohan** [comment]
Can you say how to extract information from layoutlm in question answer pair format ?

**Comment by jyothish-mohan** [comment]
Thanks
