### ISSUE TITLE
Training TrOCR with pre-trained Encoder and Decoder

### ISSUE THREAD

**Issue by RishabhMaheshwary** [NielsRogge/Transformers-Tutorials#70]
Is it possible to fine-tune the TrOCR model by loading the pre-trained VIT encoder and pretrained Roberta Decoder and not the pretrained TrOCR model i.e. ```microsoft/trocr-base-stage1```.?
If yes, than how should the config look like.

Thanks

**Comment by NielsRogge** [comment]
Yes that is totally possible! You can initialize a VisionEncoderDecoderModel with any encoder and decoder you'd like, for instance:

```
from transformers import VisionEncoderDecoderModel

# initialize the encoder from a pretrained ViT and the decoder from a pretrained BERT model. Note that the cross-attention layers will be randomly initialized, and need to be fine-tuned on a downstream dataset
model = VisionEncoderDecoderModel.from_encoder_decoder_pretrained(
    "google/vit-base-patch16-224-in21k", "bert-base-uncased"
)
# saving model after fine-tuning
model.save_pretrained("./vit-bert")
# load fine-tuned model
model = VisionEncoderDecoderModel.from_pretrained("./vit-bert")
```

**Comment by RishabhMaheshwary** [comment]
Thanks for the reply!

**Comment by CrasCris** [comment]
> Yes that is totally possible! You can initialize a VisionEncoderDecoderModel with any encoder and decoder you'd like from the hub, for instance:
> 
> ```
> from transformers import VisionEncoderDecoderModel
> 
> # initialize the encoder from a pretrained ViT and the decoder from a pretrained BERT model. 
> # Note that the cross-attention layers will be randomly initialized, and need to be fine-tuned on a downstream dataset
> model = VisionEncoderDecoderModel.from_encoder_decoder_pretrained(
>     "google/vit-base-patch16-224-in21k", "bert-base-uncased"
> )
> # set decoder config to causal lm
> model.config.decoder.is_decoder = True
> model.config.decoder.add_cross_attention = True
> # saving model after fine-tuning
> model.save_pretrained("./vit-bert")
> # load fine-tuned model
> model = VisionEncoderDecoderModel.from_pretrained("./vit-bert")
> ```

is it need to be resize the input image of the model if the decoder and the encoder are change ?
