### ISSUE TITLE
Token classification using LayoutXLM

### ISSUE THREAD

**Issue by manangandhi7** [NielsRogge/Transformers-Tutorials#76]
Model : LayoutXLM

I am able to use LayoutLMv2ForTokenClassification for my problem. Since the data I am using is in German, I would like to use LayoutXLM model. Unfortunately I do not find LayoutLXLMForTokenClassification on Transformers. How could I do Token classification using LayoutXLM?

To Reproduce

from transformers import LayoutXLMForTokenClassification
Expected behavior
ImportError: cannot import name 'LayoutXLMForTokenClassification' from 'transformers' (/opt/conda/lib/python3.7/site-packages/transformers/init.py)

Platform: Linux
Python version: 3.7

**Comment by NielsRogge** [comment]
Hi,

LayoutXLM is identical to LayoutLMv2. There's no LayoutXLM models defined in the library. You can just use:

```
from transformers import LayoutLMv2ForTokenClassification

model = LayoutLMv2ForTokenClassification.from_pretrained("microsoft/layoutxlm-base")
```

**Comment by NielsRogge** [comment]
Which version of Transformers are you on?

**Comment by manangandhi7** [comment]
python 3.7
transformers 4.16.2
torch 1.10.2+cu102

**Comment by manangandhi7** [comment]
Issue is resolved when I downgrade transformers to v4.15.0

**Comment by NielsRogge** [comment]
Thanks, I could reproduce the issue and have reported it. We will fix it.

**Comment by NielsRogge** [comment]
Update: fixed per https://github.com/huggingface/transformers/pull/15629.

We will do a patch release on Monday. For now, you can install Transformers from master: pip install git+https://github.com/huggingface/transformers.git.

Will close this issue.
