### ISSUE TITLE
About LayoutXLM (Fine-tuning code)

### ISSUE THREAD

**Issue by yellowjs0304** [NielsRogge/Transformers-Tutorials#87]
Hi @NielsRogge , Thank you for sharing nice work.
I really sorry, but I can't getting exactly about Layoutxlm.

I saw all the issues about layoutlmv2, layoutxlm, but I can't understand right.

I want to fine-tuning layoutxlm model with CORD dataset, also with my own dataset, So I used the LayoutLMv2/CORD/Fine_tuning_LayoutLMv2ForTokenClassification_on_CORD.ipynb

Is this right that I only modify the model path(in cell 21) as below?
```
# before
model = LayoutLMv2ForTokenClassification.from_pretrained('microsoft/layoutlmv2-base-uncased', num_labels=len(labels))
# after
model = LayoutLMv2ForTokenClassification.from_pretrained('microsoft/layoutxlm-base', num_labels=len(labels))
```

or Am I must modify the processor(in cell 12), tokenizers too?
```
# before
processor = LayoutLMv2Processor.from_pretrained("microsoft/layoutlmv2-base-uncased", revision="no_ocr")
# after
processor = LayoutXLMProcessor.from_pretrained("microsoft/layoutxlm-base")
```
(I saw that there are LayoutXLMProcessor, LayoutXLMTokenizer, LayoutXLMTokenizerFast)

Sorry for asking the same question repeatedly.

**Comment by yellowjs0304** [comment]
Any advice would be really appreciated. @NielsRogge

**Comment by NielsRogge** [comment]
Hi,

Yes you should use both the processor and model from `microsoft/layoutxlm-base`.

**Comment by yellowjs0304** [comment]
Thank you for fast reply. I'll try it.
