### ISSUE TITLE
Inference on custom data

### ISSUE THREAD

**Issue by sindhuattaiger** [NielsRogge/Transformers-Tutorials#9]
How do I modify the FUNSDDataset class for inference on custom data, where I do not have annotations?

**Comment by NielsRogge** [comment]
Hi,

Yes my notebook includes an inference section, which shows how you can annotate new, unseen data. I'm using Google's Tesseract OCR engine to detect the bounding boxes.

See [this notebook](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLM/Add_image_embeddings_to_LayoutLM.ipynb), at the end.

**Comment by sindhuattaiger** [comment]
But this works only for the FUNSD test set, which comes along with annotations. 
How to do inference on a new image which has no labels?

**Comment by sindhuattaiger** [comment]
Let me take a look. I believe its something like the one mentioned in [this notebook](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLM/Fine_tuning_LayoutLMForTokenClassification_on_FUNSD.ipynb)

However, Im still a bit confused on adding the image embedding part

**Comment by sindhuattaiger** [comment]
#

> Hi,
> 
> Yes my notebook includes an inference section, which shows how you can annotate new, unseen data. I'm using Google's Tesseract OCR engine to detect the bounding boxes.
> 
> See [this notebook](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLM/Add_image_embeddings_to_LayoutLM.ipynb), at the end.

This works!👍🏻

**Comment by sindhuattaiger** [comment]
> Just in the same way, first apply OCR on it to get the text + bounding boxes. Then, tokenize these using `LayoutLMTokenizer`. Then, provide this to `LayoutLMForTokenClassification`. Finally, visualize the result. All of this is shown in the notebook linked above.

This one worked and I could replicate the results.

**Comment by abdksyed** [comment]
Hi,
Thanks for such great tutorials.

But I had a question regarding OCR, my images are kind of forms, which have both printed text and also hand written text and the quality of the images are not that great, they are scanned so they are with black noise around, some with high contrast etc.

The Google Tesseract OCR is very poor in identifying the words, it is able to identify the bounding box to some extent, but the words are not at all correct. LayoutLM can't be used to predict the words??
Is LayoutLM only used for classification of words(tokens),

Another use case for me is document layout analysis, where the model has to drawing bounding boxes around the regions like tables and paragraph etc, which I couldn't find in LayoutLM, it's doing only classification of words by taking bounding box and text from OCR.

**Comment by NielsRogge** [comment]
> Is LayoutLM only used for classification of words(tokens)?

Yes. LayoutLM relies on an external OCR engine to get a list of words + bounding boxes, which it then uses to either classify the document (with `LayoutLMForSequenceClassification`) or label the words (with `LayoutLMForTokenClassification`).
So here, my advise is to use a different OCR engine.

> Another use case for me is document layout analysis, where the model has to drawing bounding boxes around the regions like tables and paragraph etc.

LayoutLM is mainly intended for classifying document images/extract information from them. For document layout analysis, I'd recommend checking out LayoutParser: https://github.com/Layout-Parser/layout-parser

**Comment by abdksyed** [comment]
Thanks for such quick response,
So LayoutLM is for classification of entire document page or each word, not doing OCR by itself or anything.

Yeah, on Layout Parser I tried it, the pre trained models are not working that great, will have to annotate my dataset and fine tine those models for layout analysis.

Also, by any chance do you know any good Hand Written Text Recognition models, like Tesseract etc. From online posts blogs, tesseract is good only for printed text, and not for handwritten text.

**Comment by NielsRogge** [comment]
You can check out DocTR: https://github.com/mindee/doctr
