### ISSUE TITLE
Meta-DETR contribution

### ISSUE THREAD

**Issue by NouamaneTazi** [NielsRogge/Transformers-Tutorials#92]
Hello! I would like to incorporate meta-learning to your DETR implementation to perform few-shot object detection. Any suggestions where to start? 

Link to the paper https://arxiv.org/abs/2103.11731
Link to the official implementation https://github.com/ZhangGongjie/Meta-DETR

**Comment by NielsRogge** [comment]
Hi,

Yes it would be cool that have Meta-DETR in HuggingFace Transformers! For this, we would probably add a separate model (`MetaDetrModel`, `MetaDetrForObjectDetection` etc.).

We prefer to have a "one model, one file" philosophy, even duplicating code per paper to keep it clean.

Let me know if you're interested in opening a PR on HuggingFace Transformers

**Comment by NouamaneTazi** [comment]
Yes I would like to!

**Comment by NielsRogge** [comment]
If it's ok for you, I'll set up a Slack channel with your email address found on your Github profile.

**Comment by NouamaneTazi** [comment]
Sure!

**Comment by NouamaneTazi** [comment]
It seems I'll need to implement Deformable DETR first: https://github.com/fundamentalvision/Deformable-DETR . Since it's the architecture used for Meta DETR

**Comment by NielsRogge** [comment]
Hi, 

I do have a HuggingFace implementation for Deformable DETR: https://github.com/NielsRogge/transformers/tree/add_deformable_detr/src/transformers/models/deformable_detr

However I have to fix 2 tests for the model, then I can open up a PR on HuggingFace Transformers.

**Comment by NouamaneTazi** [comment]
Perfect! I'll try to use it for Meta-DETR. Tell me if you need help with the PR

**Comment by NielsRogge** [comment]
I've sent you an invite for Slack :)

**Comment by NouamaneTazi** [comment]
I can't join, It seems I need a paid plan to use the Slack Connect channel invitation: https://slack.com/help/articles/360049769934-Accept-a-Slack-Connect-channel-invitation

**Comment by NielsRogge** [comment]
Normally you should have received a new invite now
