### ISSUE TITLE
LayoutXLM Procedure

### ISSUE THREAD

**Issue by LucaWeissbeck** [NielsRogge/Transformers-Tutorials#95]
Hi there,

I know that the repository does not contain the LayoutXLM model per se, but I was wondering if there was an easy way to fine tune the LayoutXLM mode or rather if the process is identical to the LayoutLMv2 model, which you described in great detail with the FUNSD dataset. 
However, there does not seem to be a "no-ocr" revision for the LayoutXLM dataset on huggingface.
Upon request in the original repository for LayoutXLM (Microsoft/unilm) someone suggested doing this for loading the processor:
```python3
tokenizer = LayoutXLMTokenizerFast.from_pretrained(processor_name)
processor_no_ocr = LayoutXLMProcessor(LayoutLMv2FeatureExtractor(apply_ocr=False), tokenizer)
```

instead of:
``` python3
LayoutLMv2Processor.from_pretrained("microsoft/layoutlmv2-base-uncased", revision="no_ocr") 
```

However when parsing "microsoft/layoutxlm-base" as the processor name, there seems to be an error in the data format. Is there maybe a better way to do this or would this include a further substantial amount of work? The reason I want to do this is because my model will also be reading in invoices in German instead of English.
Thank you! :)

The error:
```
ValueError: Couldn't cast
image: extension<arrow.py_extension_type<Array3DExtensionType>>
input_ids: list<item: int64>
  child 0, item: int64
attention_mask: list<item: int64>
  child 0, item: int64
bbox: extension<arrow.py_extension_type<Array2DExtensionType>>
labels: list<item: int64>
  child 0, item: int64
-- schema metadata --
huggingface: '{"info": {"features": {"image": {"shape": [3, 224, 224], "d' + 500
to
{'image': Array3D(shape=(3, 224, 224), dtype='int64', id=None), 'input_ids': Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None), 'attention_mask': Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None), 'token_type_ids': Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None), 'bbox': Array2D(shape=(512, 4), dtype='int64', id=None), 'labels': Sequence(feature=ClassLabel(num_classes=11, names=['O', 'B-INVOICE_NUMBER', 'I-INVOICE_NUMBER', 'B-ITEM_PRICE', 'I-ITEM_PRICE', 'B-ITEM_NAME', 'I-ITEM_NAME', 'B-TOTAL_PRICE', 'I-TOTAL_PRICE', 'B-DATE', 'I-DATE'], id=None), length=-1, id=None)}
because column names don't match
```

**Comment by lyonguyen8697** [comment]
I have the same issue when training LayoutXLM.
Changing this code from:
```python
  encoded_inputs = processor(images, words, boxes=boxes, word_labels=word_labels,
                             padding="max_length", truncation=True)
```
to:
```python
  encoded_inputs = processor(images, words, boxes=boxes, word_labels=word_labels,
                             padding="max_length", truncation=True, max_length=512, return_token_type_ids=True)
```
solved my problem.

**Comment by LucaWeissbeck** [comment]
> I have the same issue when training LayoutXLM. Changing this code from:
> 
> ```python
>   encoded_inputs = processor(images, words, boxes=boxes, word_labels=word_labels,
>                              padding="max_length", truncation=True)
> ```
> 
> to:
> 
> ```python
>   encoded_inputs = processor(images, words, boxes=boxes, word_labels=word_labels,
>                              padding="max_length", truncation=True, max_length=512, return_token_type_ids=True)
> ```
> 
> solved my problem.

That was an easy fix, thank you so much for the help! :)
