### ISSUE TITLE
Still have a problem with LayoutXLMProcessor

### ISSUE THREAD

**Issue by yellowjs0304** [NielsRogge/Transformers-Tutorials#98]
@NielsRogge First of all, Thank you for sharing your works.
this is the issue when training LayoutXLM models. 
I think there's something problem in Processor.
![image](https://user-images.githubusercontent.com/30281608/160511528-749ee551-6ef9-446a-a875-3abac92a32ec.png)

![image](https://user-images.githubusercontent.com/30281608/160511008-328270f9-098d-4d65-a2c9-0fceb5a89639.png)

Could you please check this issue?? 😢

**Comment by lyonguyen8697** [comment]
I have the same issue when training LayoutXLM.
Changing this code from:
```python
  encoded_inputs = processor(images, words, boxes=boxes, word_labels=word_labels,
                             padding="max_length", truncation=True)
```
to:
```python
  encoded_inputs = processor(images, words, boxes=boxes, word_labels=word_labels,
                             padding="max_length", truncation=True, max_length=512, return_token_type_ids=True)
```
solved my problem.

**Comment by yellowjs0304** [comment]
@lyonguyen8697 Great! Thank you so much.
